import { getApiActor } from "@/lib/api/auth";
import { apiBackendError, apiError, apiSuccess } from "@/lib/api/responses";
import { getPublishedLessonRouteData } from "@/lib/data/published-catalog";
import { checkFlashRecall, flashRecallFinishSchema, flashRecallRules, gradeFlashRecall, scoreFlashRecall, type FlashRecallQuestion } from "@/lib/speed-test/flash-recall-domain";
import { calculateSpeedRating } from "@/lib/speed-test/domain";
import { getLessonLearningProgress } from "@/lib/data/lesson-progress";

export async function POST(request: Request) {
  const actor=await getApiActor(request); if(!actor)return apiError("UNAUTHENTICATED","Bạn cần đăng nhập.",401);
  const parsed=flashRecallFinishSchema.safeParse(await request.json().catch(()=>null)); if(!parsed.success)return apiError("VALIDATION_ERROR","Kết quả Flash Recall không hợp lệ.",422); const input=parsed.data;
  const data=await getPublishedLessonRouteData(input.courseSlug,input.lessonSlug); if(!data)return apiError("LESSON_NOT_FOUND","Không tìm thấy bài học.",404);
  const lessonProgress=await getLessonLearningProgress({supabase:actor.supabase,userId:actor.user.id,lesson:data.lesson});
  if(!lessonProgress.speedTestUnlocked)return apiError("SPEED_TEST_LOCKED",`Bạn cần đạt ${lessonProgress.unlockThreshold}% tiến độ bài học để mở Speed Test.`,403,{completionPercent:lessonProgress.completionPercent,unlockThreshold:lessonProgress.unlockThreshold});
  const expectedCount=flashRecallRules.levels[input.level].questions; if(input.questionIds.length!==expectedCount||new Set(input.questionIds).size!==expectedCount)return apiError("INVALID_QUESTIONS","Danh sách câu hỏi không hợp lệ.",422);
  const source=new Map<string,FlashRecallQuestion>(data.lesson.vocabulary.flatMap(item=>(["ko_vi","vi_ko"] as const).map(actual=>{const expected=actual==="ko_vi"?item.vietnamese:item.korean;const question:FlashRecallQuestion={id:`recall:${actual}:${item.id}`,vocabularyId:item.id,type:"word",imageUrl:item.imageUrl,prompt:actual==="ko_vi"?item.korean:item.vietnamese,expected,direction:actual,accepted:actual==="ko_vi"?[item.vietnamese,...(item.acceptedVietnameseAnswers??[])]:[item.korean,...(item.acceptedKoreanAnswers??[])],options:[]};return [question.id,question] as const;}))); if(input.questionIds.some(id=>!source.has(id)))return apiError("QUESTION_NOT_FOUND","Câu hỏi không thuộc bài học.",409);
  let combo=0,bestCombo=0,score=0,lives=5,perfect=0,great=0,good=0; const answers=[];
  for(const submitted of input.answers){const q=source.get(submitted.questionId);if(!q)return apiError("QUESTION_NOT_FOUND","Câu hỏi không hợp lệ.",409);const correct=checkFlashRecall(submitted.userAnswer,q);combo=correct?combo+1:0;if(!correct)lives--;bestCombo=Math.max(bestCombo,combo);const grade=gradeFlashRecall(input.level,correct,submitted.recallTimeMs);if(grade==="perfect")perfect++;if(grade==="great")great++;if(grade==="good")good++;const points=scoreFlashRecall(input.level,grade,combo)*(combo>=10?2:1);score+=points;answers.push({questionId:q.id,vocabularyId:q.vocabularyId,userAnswer:submitted.userAnswer,reactionTimeMs:submitted.recallTimeMs,position:submitted.position,prompt:q.prompt,expectedAnswer:q.expected,result:correct?"correct":"wrong",questionType:"word",grade,points,streakMultiplier:combo>=10?2:combo>=5?1.5:combo>=3?1.2:1,difficulty:flashRecallRules.levels[input.level].multiplier,audioDurationMs:null,answerWindowMs:flashRecallRules.levels[input.level].answerMs});}
  const correctCount=answers.filter(a=>a.result==="correct").length,wrongCount=answers.length-correctCount,accuracy=answers.length?Math.round(correctCount/answers.length*10000)/100:0,completed=answers.length===expectedCount&&lives>0;
  const {data:previous}=await actor.supabase.from("speed_test_records").select("highest_score,fastest_time_ms").eq("user_id",actor.user.id).eq("source_id",data.lesson.id).eq("game_type","flash_reaction").eq("difficulty_level",input.level).eq("reaction_direction",input.direction).eq("scoring_version",flashRecallRules.version).maybeSingle();
  const previousScore=Number(previous?.highest_score??0),previousTime=previous?.fastest_time_ms==null?Infinity:Number(previous.fastest_time_ms);
  const totalTimeMs=flashRecallRules.levels[input.level].totalMs-input.remainingMs;
  const {error}=await actor.supabase.rpc("save_audio_reaction_result",{p_attempt:{id:input.attemptId,lessonId:data.lesson.id,lessonName:`Bài ${data.lesson.order}: ${data.lesson.title.vi}`.slice(0,60),gameType:"flash_reaction",direction:input.direction==="vi_ko"?"vi_ko":"ko_vi",requestedQuestionCount:String(expectedCount),totalQuestions:expectedCount,answeredCount:answers.length,correctCount,wrongCount,accuracy,bestCombo,rating:calculateSpeedRating({accuracy,completed}),completed,scoringVersion:flashRecallRules.version,questionIds:input.questionIds,startedAt:input.startedAt,finishedAt:input.finishedAt,mode:flashRecallRules.levels[input.level].mode,score,totalTimeMs,livesRemaining:lives,perfectCount:perfect,greatCount:great,goodCount:good,missCount:wrongCount,gameOver:!completed},p_answers:answers}); if(error)return apiBackendError(error,"Chưa thể lưu Flash Recall.");
  const {error:metadataError}=await actor.supabase.rpc("update_flash_recall_metadata",{p_attempt_id:input.attemptId,p_level:input.level,p_direction:input.direction,p_answers:answers});if(metadataError)return apiBackendError(metadataError,"Đã lưu session nhưng chưa thể cập nhật Memory Strength.");
  let ranking:unknown=null;const {data:rankedData,error:rankedError}=await actor.supabase.rpc("register_ranked_speed_attempt",{p_attempt_id:input.attemptId});if(!rankedError)ranking=rankedData;
  return apiSuccess({score,accuracy,bestCombo,perfectCount:perfect,correctCount,wrongCount,personalBest:{highestScore:score>previousScore,fastestTime:completed&&totalTimeMs<previousTime},ranking});
}
