import { notFound } from "next/navigation";
import Link from "next/link";
import Image from "next/image";
import { getExamForEditing } from "@/lib/data/exams";
import { changeExamRelease, publishExam, reviewExam } from "@/features/exams/actions";
import { answerReviewPolicyLabel } from "@/lib/exams/answer-review-policy";
import type { ExamAnswerReviewPolicy } from "@/lib/exams/types";

export default async function AdminExamDetailPage({ params, searchParams }: { params: Promise<{ examId: string }>; searchParams: Promise<{ error?: string }> }) {
  const [{ examId }, notice] = await Promise.all([params, searchParams]);
  const exam = await getExamForEditing(examId); if (!exam) notFound();
  return <main className="mx-auto max-w-6xl px-5 py-10">
    <Link href="/quan-tri/de-thi" className="font-black text-violet-700">← Danh sách đề</Link>
    <div className="mt-5 flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-widest text-violet-600">{exam.code} · {exam.status}</p><h1 className="mt-2 text-4xl font-black">{exam.title}</h1><p className="mt-3 text-slate-600">{exam.level === "topik_ii" ? "TOPIK II" : "TOPIK I"} · {exam.exam_questions?.length ?? 0} câu · Nghe {exam.listening_duration_minutes} phút · Đọc {exam.reading_duration_minutes} phút</p><p className="mt-2 text-sm font-bold text-violet-700">Đáp án: {answerReviewPolicyLabel((exam.answer_review_policy ?? "immediate") as ExamAnswerReviewPolicy)}{exam.answer_review_policy === "after_date" && exam.answer_review_available_at ? ` · ${new Date(exam.answer_review_available_at).toLocaleString("vi-VN")}` : ""}</p></div><div className="flex flex-wrap gap-2">{exam.status === "approved" && <><form action={publishExam}><input type="hidden" name="examId" value={exam.id} /><button className="rounded-2xl bg-violet-600 px-5 py-3 font-black text-white">Phát hành đề →</button></form><form action={changeExamRelease}><input type="hidden" name="examId" value={exam.id} /><button name="releaseAction" value="cancel_approval" className="rounded-2xl border bg-white px-5 py-3 font-black">Hủy phê duyệt</button></form></>}{exam.status === "published" && <><Link href={`/quan-tri/de-thi/${exam.id}/hotfix`} className="rounded-2xl bg-amber-500 px-5 py-3 font-black text-white">Hotfix đề</Link><form action={changeExamRelease}><input type="hidden" name="examId" value={exam.id} /><button name="releaseAction" value="unpublish" className="rounded-2xl border border-red-200 bg-red-50 px-5 py-3 font-black text-red-700">Tạm gỡ đề</button></form></>}</div></div>
    {notice.error && <p className="mt-5 rounded-2xl bg-red-50 p-4 font-bold text-red-700">{notice.error}</p>}
    {exam.status === "pending_review" && <div className="mt-5 flex justify-end"><Link href={`/quan-tri/de-thi/${exam.id}/chinh-sua`} className="rounded-2xl border border-violet-200 bg-violet-50 px-5 py-3 font-black text-violet-700">Chỉnh sửa nhanh</Link></div>}
    <section className="mt-7 space-y-4">{(exam.exam_questions ?? []).map((q: { id: string; position: number; section: string; instruction: string; prompt: string; audio_url: string | null; image_url: string | null; options: unknown; correct_option: number; explanation: string }) => <article key={q.id} className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-widest text-cyan-700">{q.section === "reading" ? "Đọc" : "Nghe"} · Câu {q.position}</p><h2 className="mt-2 text-lg font-black">{q.prompt || q.instruction}</h2></div>{q.section === "listening" && (q.audio_url ? <audio controls preload="none" src={q.audio_url} className="h-10" /> : <span className="rounded-full bg-red-100 px-3 py-1 text-xs font-black text-red-700">Thiếu audio</span>)}</div>{q.image_url && <Image unoptimized src={q.image_url} alt={`Minh họa câu ${q.position}`} width={800} height={500} className="mt-4 max-h-72 w-auto rounded-2xl object-contain" />}<div className="mt-4 grid gap-2 sm:grid-cols-2">{(Array.isArray(q.options) ? q.options : []).map((option, index) => <p key={index} className={`rounded-xl p-3 font-bold ${index + 1 === q.correct_option ? "bg-emerald-100 text-emerald-800" : "bg-slate-50"}`}>{index + 1}. {String(option)}</p>)}</div>{q.explanation && <p className="mt-3 text-sm font-semibold text-slate-600">Giải thích: {q.explanation}</p>}</article>)}</section>
    {exam.status === "pending_review" && <form action={reviewExam} className="sticky bottom-4 mt-7 rounded-3xl border bg-white/95 p-5 shadow-xl backdrop-blur"><input type="hidden" name="examId" value={exam.id} /><label className="font-black">Nhận xét<textarea name="note" className="mt-2 min-h-24 w-full rounded-2xl border px-4 py-3" placeholder="Nêu điểm đạt hoặc nội dung cần sửa..." /></label><div className="mt-4 flex flex-wrap gap-3"><button name="decision" value="approved" className="rounded-xl bg-emerald-600 px-5 py-3 font-black text-white">Phê duyệt</button><button name="decision" value="changes_requested" className="rounded-xl border border-amber-300 bg-amber-50 px-5 py-3 font-black text-amber-800">Yêu cầu chỉnh sửa</button></div></form>}
  </main>;
}
