"use client";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import type { VocabularyItem } from "@/content/schema";
import type { SpeedTestWordProgress } from "@/lib/speed-test/domain";
import { buildFlashRecallQuestions, checkFlashRecall, flashRecallLevels, flashRecallRules, gradeFlashRecall, scoreFlashRecall, type FlashRecallDirection, type FlashRecallGrade, type FlashRecallLevel, type FlashRecallQuestion } from "@/lib/speed-test/flash-recall-domain";
import { GameMusicControl, useGameBackgroundMusic } from "./game-background-music";

type Stage = "setup" | "countdown" | "playing" | "result";
type Phase = "show" | "recall" | "feedback";
type Answer = { questionId: string; userAnswer: string; recallTimeMs: number; position: number; correct: boolean; grade: FlashRecallGrade; points: number };
function format(ms: number) { return `${Math.floor(ms / 60000).toString().padStart(2,"0")}:${((ms % 60000) / 1000).toFixed(1).padStart(4,"0")}`; }
function playRecallSound(kind:"correct"|"wrong"|"rush"){try{const C=window.AudioContext??(window as typeof window&{webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=kind==="wrong"?160:kind==="rush"?960:680;o.type=kind==="wrong"?"sawtooth":"sine";g.gain.setValueAtTime(.001,c.currentTime);g.gain.exponentialRampToValueAtTime(.12,c.currentTime+.01);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.22);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.24);o.addEventListener("ended",()=>void c.close(),{once:true})}catch{/* optional sound */}}

export function FlashRecallExperience({ vocabulary, lessonName, lessonId, courseSlug, lessonSlug, progressById, backHref, rankedMode = false, rankedAttemptsRemaining = 3, onBackToArena }: { vocabulary: VocabularyItem[]; lessonName: string; lessonId: string; courseSlug: string; lessonSlug: string; progressById: Record<string, SpeedTestWordProgress>; backHref: string; rankedMode?: boolean; rankedAttemptsRemaining?: number; onBackToArena?: () => void }) {
  const [stage,setStage]=useState<Stage>("setup"),[level,setLevel]=useState<FlashRecallLevel>(rankedMode?"medium":vocabulary.length>=20?"medium":"easy"),[direction,setDirection]=useState<FlashRecallDirection>("mixed"),[countdown,setCountdown]=useState(3),[questions,setQuestions]=useState<FlashRecallQuestion[]>([]),[index,setIndex]=useState(0),[phase,setPhase]=useState<Phase>("show"),[remaining,setRemaining]=useState(0),[lives,setLives]=useState(5),[combo,setCombo]=useState(0),[bestCombo,setBestCombo]=useState(0),[score,setScore]=useState(0),[value,setValue]=useState(""),[answers,setAnswers]=useState<Answer[]>([]),[feedback,setFeedback]=useState<Answer|null>(null),[sync,setSync]=useState("idle"),[personalBest,setPersonalBest]=useState({highestScore:false,fastestTime:false}),[rankedRemaining,setRankedRemaining]=useState(rankedAttemptsRemaining);
  const gameMusic=useGameBackgroundMusic(stage==="countdown"||stage==="playing");
  const deadline=useRef(0),recallAt=useRef(0),startedAt=useRef(""),attemptId=useRef(""),finishing=useRef(false),inputRef=useRef<HTMLInputElement>(null); const question=questions[index], rule=flashRecallRules.levels[level], mode=rule.mode;
  const finish=useCallback((finalAnswers:Answer[], finalRemaining:number)=>{if(finishing.current)return;finishing.current=true;setStage("result");setRemaining(Math.max(0,finalRemaining));setSync("saving");void fetch("/api/v1/flash-recalls",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({attemptId:attemptId.current,courseSlug,lessonSlug,level,direction,ranked:rankedMode,questionIds:questions.map(q=>q.id),answers:finalAnswers.map(a=>({questionId:a.questionId,userAnswer:a.userAnswer,recallTimeMs:a.recallTimeMs,position:a.position})),remainingMs:Math.max(0,Math.round(finalRemaining)),startedAt:startedAt.current,finishedAt:new Date().toISOString()})}).then(async r=>{const payload=await r.json() as {data?:{personalBest?:{highestScore:boolean;fastestTime:boolean};ranking?:{attemptsRemaining?:number}}};if(!r.ok)throw new Error();if(payload.data?.personalBest)setPersonalBest(payload.data.personalBest);if(typeof payload.data?.ranking?.attemptsRemaining==="number")setRankedRemaining(payload.data.ranking.attemptsRemaining);setSync("saved")}).catch(()=>setSync("failed"));},[courseSlug,direction,lessonSlug,level,questions,rankedMode]);
  useEffect(()=>{if(stage!=="countdown")return;const id=setTimeout(()=>countdown?setCountdown(v=>v-1):(deadline.current=performance.now()+rule.totalMs,setRemaining(rule.totalMs),setStage("playing"),setPhase("show")),countdown?500:250);return()=>clearTimeout(id)},[countdown,rule.totalMs,stage]);
  useEffect(()=>{if(stage!=="playing")return;const id=setInterval(()=>{const next=Math.max(0,deadline.current-performance.now());setRemaining(next);if(!next)finish(answers,0)},50);return()=>clearInterval(id)},[answers,finish,stage]);
  useEffect(()=>{if(stage!=="playing"||phase!=="show"||!question)return;const rush=combo>=10?.65:combo>=5?.82:1,duration=rule.showMs*rush;document.documentElement.style.setProperty("--flash-recall-show-duration",`${duration}ms`);const id=setTimeout(()=>{recallAt.current=performance.now();setPhase("recall");setTimeout(()=>inputRef.current?.focus(),0)},duration);return()=>clearTimeout(id)},[combo,phase,question,rule.showMs,stage]);
  const submit=useCallback((answer:string)=>{if(!question||phase!=="recall")return;const ms=Math.round(performance.now()-recallAt.current),correct=checkFlashRecall(answer,question),nextCombo=correct?combo+1:0,nextLives=correct?lives:lives-1,grade=gradeFlashRecall(level,correct,ms),points=scoreFlashRecall(level,grade,nextCombo)*(combo>=10?2:1),item={questionId:question.id,userAnswer:answer.trim(),recallTimeMs:ms,position:answers.length+1,correct,grade,points},next=[...answers,item];playRecallSound(!correct?"wrong":nextCombo===5||nextCombo===10?"rush":"correct");setAnswers(next);setFeedback(item);setPhase("feedback");setCombo(nextCombo);setBestCombo(v=>Math.max(v,nextCombo));setScore(v=>v+points);setLives(nextLives);setTimeout(()=>{setFeedback(null);setValue("");if(nextLives<=0||index+1>=questions.length)finish(next,deadline.current-performance.now());else{setIndex(v=>v+1);setPhase("show")}},correct?600:1000)},[answers,combo,finish,index,level,lives,phase,question,questions.length]);
  useEffect(()=>{if(stage!=="playing"||phase!=="recall")return;const id=setTimeout(()=>submit(""),rule.answerMs);return()=>clearTimeout(id)},[phase,rule.answerMs,stage,submit]);
  useEffect(()=>{if(sync==="saved"&&(personalBest.highestScore||personalBest.fastestTime))playRecallSound("rush")},[personalBest,sync]);
  function start(){if(vocabulary.length<rule.questions)return;gameMusic.playFromUserGesture();setQuestions(buildFlashRecallQuestions({vocabulary,level,direction,progressById:rankedMode?{}:progressById}));setIndex(0);setAnswers([]);setLives(5);setCombo(0);setBestCombo(0);setScore(0);setPersonalBest({highestScore:false,fastestTime:false});setCountdown(3);setStage("countdown");finishing.current=false;startedAt.current=new Date().toISOString();attemptId.current=crypto.randomUUID()}
  if(stage==="setup")return <FlashRecallSetup vocabularyCount={vocabulary.length} lessonName={lessonName} level={level} direction={direction} setLevel={setLevel} setDirection={setDirection} backHref={backHref} onStart={start} rankedMode={rankedMode} rankedRemaining={rankedRemaining}/>;
  if(stage==="countdown")return <main className="grid min-h-dvh place-items-center bg-violet-950 text-center text-white"><GameMusicControl enabled={gameMusic.enabled} volume={gameMusic.volume} toggle={gameMusic.toggle} setVolume={gameMusic.setVolume}/><div><p className="font-black tracking-[.3em] text-fuchsia-300">SẴN SÀNG GHI NHỚ?</p><b className="mt-4 block text-[9rem]">{countdown||"GO!"}</b></div></main>;
  if(stage==="result"&&sync==="saved"&&(personalBest.highestScore||personalBest.fastestTime))return <main className="grid min-h-dvh place-items-center overflow-hidden bg-[radial-gradient(circle,#fef08a,#7c3aed_52%,#1e1b4b)] p-5 text-center text-white"><section className="animate-bounce rounded-[2.5rem] border border-amber-200 bg-violet-950/80 p-10 shadow-[0_0_90px_rgba(250,204,21,.55)]"><p className="text-6xl">🏆</p><h1 className="mt-4 text-4xl font-black text-amber-300 sm:text-6xl">KỶ LỤC CÁ NHÂN MỚI!</h1><p className="mt-3 text-xl font-bold">{personalBest.highestScore?"Điểm cao nhất":"Thời gian hoàn thành nhanh nhất"}</p><button onClick={()=>setPersonalBest({highestScore:false,fastestTime:false})} className="mt-7 rounded-2xl bg-amber-300 px-7 py-4 font-black text-violet-950">XEM KẾT QUẢ →</button></section></main>;
  if(stage==="result"){const correct=answers.filter(a=>a.correct).length,perfect=answers.filter(a=>a.grade==="perfect").length,accuracy=answers.length?Math.round(correct/answers.length*100):0,memory=Math.round(accuracy*.7+Math.min(100,perfect/Math.max(1,answers.length)*100)*.3);return <main className="min-h-dvh bg-violet-950 p-5 text-white"><section className="mx-auto max-w-3xl rounded-[2.5rem] bg-white/10 p-8 text-center"><p className="font-black tracking-[.2em] text-fuchsia-300">🧠 FLASH RECALL {lives?"COMPLETE":"GAME OVER"}</p><h1 className="mt-3 text-7xl font-black text-amber-300">{score.toLocaleString("vi-VN")}</h1><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3">{[[`⏱ ${format(rule.totalMs-remaining)}`,"Thời gian"],[`🎯 ${accuracy}%`,"Chính xác"],[`🔥 ${bestCombo}`,"Best streak"],[`⚡ ${perfect}`,"Perfect"],[`✕ ${answers.length-correct}`,"Sai"],[`${memory}%`,"Memory Strength"]].map(([v,l])=><div key={l} className="rounded-2xl bg-white/10 p-4 text-left"><b className="text-xl">{v}</b><span className="block text-xs text-white/55">{l}</span></div>)}</div><p className="mt-5 text-sm text-white/55">{sync==="saving"?"Đang lưu…":sync==="saved"?"✓ Recall time và kết quả đã lưu":sync==="failed"?"Không thể lưu kết quả":""}</p><div className="mt-7 grid gap-3 sm:grid-cols-3"><button onClick={()=>setStage("setup")} className="rounded-xl bg-amber-300 p-4 font-black text-violet-950">CHƠI LẠI</button><Link href={`/speed-test/lich-su?sourceId=${lessonId}`} className="rounded-xl bg-violet-600 p-4 font-black">LỊCH SỬ</Link>{onBackToArena?<button onClick={onBackToArena} className="rounded-xl bg-white/10 p-4 font-black">← CHỌN THỬ THÁCH KHÁC</button>:<Link href="/speed-test" className="rounded-xl bg-white/10 p-4 font-black">← CHỌN THỬ THÁCH KHÁC</Link>}</div></section></main>}
  return <main className={`grid min-h-dvh place-items-center p-4 text-white ${feedback&&!feedback.correct?"bg-red-950":"bg-[radial-gradient(circle_at_top,#7c3aed,#1e1b4b_65%)]"}`}><GameMusicControl enabled={gameMusic.enabled} volume={gameMusic.volume} toggle={gameMusic.toggle} setVolume={gameMusic.setVolume}/><section className="w-full max-w-4xl"><header className="grid grid-cols-3 rounded-2xl bg-white/10 p-4 font-black"><span>{Array.from({length:5},(_,i)=><span key={i}>{i<lives?"❤️":"🖤"}</span>)}</span><span className="text-center">🔥 {combo}{combo>=10?" · MEMORY RUSH ×2":""}</span><span className="text-right">⏱ {format(remaining)}</span></header><div className="mt-5 grid min-h-[28rem] place-items-center rounded-[2.5rem] bg-white/95 p-7 text-center text-violet-950 shadow-2xl">{phase==="show"?<div className="animate-pulse"><p className="font-black tracking-widest text-violet-500">GHI NHỚ</p><h1 className="mt-6 text-6xl font-black">{question?.prompt}</h1></div>:phase==="recall"?<div className="w-full max-w-xl"><p className="text-7xl font-black text-violet-300">?</p><h1 className="mt-2 text-3xl font-black">Bạn còn nhớ nghĩa là gì?</h1>{mode==="choose"?<div className="mt-6 grid gap-3">{question.options.map(x=><button key={x} onClick={()=>submit(x)} className="rounded-xl bg-violet-50 p-4 text-left font-black hover:bg-violet-100">{x}</button>)}</div>:<form onSubmit={e=>{e.preventDefault();if(value.trim())submit(value)}} className="mt-6 flex gap-2"><input ref={inputRef} value={value} onChange={e=>setValue(e.target.value)} className="min-w-0 flex-1 rounded-xl border-2 border-violet-200 px-4" placeholder="Nhập đáp án…"/><button className="rounded-xl bg-violet-600 px-5 font-black text-white">TRẢ LỜI</button></form>}</div>:<div className={feedback?.correct?"text-emerald-600":"text-red-600"}><h1 className="text-5xl font-black">{feedback?.correct?(feedback.grade==="perfect"?"⚡ PERFECT!":"✓ CHÍNH XÁC"):"✕ SAI"}</h1><p className="mt-3 text-xl font-black">{feedback?.correct?`+${feedback.points}`:`Đáp án: ${question.expected}`}</p></div>}</div></section></main>;
}

function FlashRecallSetup({vocabularyCount,lessonName,level,direction,setLevel,setDirection,backHref,onStart,rankedMode,rankedRemaining}:{vocabularyCount:number;lessonName:string;level:FlashRecallLevel;direction:FlashRecallDirection;setLevel:(value:FlashRecallLevel)=>void;setDirection:(value:FlashRecallDirection)=>void;backHref:string;onStart:()=>void;rankedMode:boolean;rankedRemaining:number}){
  const rule=flashRecallRules.levels[level];
  const levelStyle:Record<FlashRecallLevel,string>={easy:"border-emerald-400 bg-emerald-300 text-emerald-950 shadow-emerald-200",medium:"border-emerald-400 bg-emerald-300 text-emerald-950 shadow-emerald-200",hard:"border-emerald-400 bg-emerald-300 text-emerald-950 shadow-emerald-200"};
  return <main className="min-h-dvh bg-gradient-to-br from-emerald-50 via-emerald-100 to-emerald-300 p-5 text-slate-950"><section className="mx-auto max-w-4xl"><Link href={rankedMode?"/bang-xep-hang?board=flash_reaction":backHref} className="inline-flex rounded-2xl bg-white px-5 py-3 font-black text-emerald-800 shadow-md">← {rankedMode?"Bảng xếp hạng":"Quay lại"}</Link><div className="mt-6 rounded-[2.5rem] bg-white/92 p-7 shadow-2xl sm:p-10"><p className="mt-8 font-black uppercase tracking-[.25em] text-emerald-700">{rankedMode?"♛ Harutopik League":"Flash Recall"}</p><h1 className="mt-2 text-4xl font-black sm:text-6xl">{rankedMode?"Flash Recall xếp hạng":"Nhớ trước khi từ biến mất"}</h1><p className="mt-2 font-bold text-slate-500">{lessonName}</p>{rankedMode&&<div className="mt-5 flex items-center justify-between gap-3 rounded-2xl border-2 border-amber-300 bg-amber-50 p-4 font-black"><span>20 câu trộn · Mức vừa · Hai chiều</span><span className="rounded-full bg-amber-300 px-4 py-2">Còn {rankedRemaining}/3 lượt</span></div>}<h2 className="mt-7 font-black">ĐỘ KHÓ</h2><div className="mt-3 grid grid-cols-3 gap-2">{flashRecallLevels.map(item=>{const itemRule=flashRecallRules.levels[item],enabled=vocabularyCount>=itemRule.questions,selected=level===item;return <button key={item} disabled={!enabled||rankedMode} onClick={()=>setLevel(item)} className={`rounded-2xl border-2 p-3 font-black transition disabled:opacity-50 ${selected?`${levelStyle[item]} shadow-lg`:"border-slate-200 bg-white hover:border-emerald-300"}`}><span className="block">{item==="easy"?"Dễ":item==="medium"?"Vừa":"Khó"}</span><small>{itemRule.questions} câu · hiện {itemRule.showMs/1000}s</small></button>})}</div><h2 className="mt-6 font-black">CHIỀU GHI NHỚ</h2><div className="mt-3 grid gap-2 sm:grid-cols-3">{[["ko_vi","Hàn → Việt"],["vi_ko","Việt → Hàn"],["mixed","Trộn hai chiều"]].map(([item,label])=><button key={item} disabled={rankedMode} onClick={()=>setDirection(item as FlashRecallDirection)} className={`rounded-xl border-2 p-3 font-black transition disabled:cursor-not-allowed ${direction===item?"border-emerald-500 bg-emerald-500 text-white shadow-lg":"border-slate-200 bg-white hover:border-emerald-300"}`}>{label}</button>)}</div><div className="mt-6 grid grid-cols-3 overflow-hidden rounded-2xl border border-emerald-100 text-center font-black"><span className="bg-emerald-50 p-4">{rule.mode==="choose"?"Trắc nghiệm":"Gõ đáp án"}</span><span className="bg-rose-50 p-4 text-rose-700">5 mạng</span><span className="bg-amber-50 p-4 text-amber-800">{rule.totalMs/1000} giây</span></div><button onClick={onStart} disabled={vocabularyCount<rule.questions||rankedRemaining<=0} className="mt-7 w-full rounded-2xl bg-gradient-to-r from-emerald-400 to-teal-500 p-4 text-xl font-black text-emerald-950 shadow-lg transition hover:-translate-y-0.5 disabled:opacity-40">{rankedRemaining<=0?"ĐÃ HẾT LƯỢT HÔM NAY":rankedMode?"BẮT ĐẦU XẾP HẠNG ♛":"BẮT ĐẦU"}</button></div></section></main>;
}
